<div class="api2cart">
  <div class="message"></div>
  <div class="text-center">
    <a target="_blank" href="https://www.api2cart.com">
      <img src="<?php echo plugins_url('images/logo.png', __FILE__) ?>" alt="API2Cart - Unified Shopping Cart API Integration Interface">
    </a>
  </div>
  <div class="text-center">
    <p>API2Cart is a unified platform to integrate with 30+ shopping carts including Magento, Shopify, WooCommerce, Bigcommerce, OpenCart, VirtueMart and others. It makes it easy to retrieve, add, delete, update, and synchronize such store data as customers, orders, products, and categories to provide different B2B services. </p>
  </div>

  <div class="container">

    <div class="text-center">
      <p id="connector-installed-txt">The connector will be installed automatically. Just click the button below and have the connection between your <?php echo $cartName; ?> store and the system needed established.</p>
      <div id="content-block-manage">
        <b>Congratulations! The plugin is installed!</b><br><br>

        <ul class="list-create-account">
          <li>To complete the connection process, follow the few steps listed below:</li>
          <li>1) Create an API2Cart account.</li>
          <li>2) Add your store to the store panel by indicating its URL and cart type.</li>
          <li>3) Voila! The link between your WooCommerce store and API2Cart is established!</li>
        </ul>
        <br>
        <b>Please note.</b> Store data interaction works if you are integrated with the service only.
        It enables to retrieve, synchronize, and manipulate various information on products, categories, customers, and orders from the stores added to the store directory. For more information, schedule a call with our representative and have it all explained to you.
        <br>
      </div>
    </div>

    <div class="text-center">

      <div class="progress progress-dark progress-small progress-striped active">
        <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
      </div>

      <div class="store-key">
        <span class="store-key-title">Your store key:</span>
        <span class="store-key-content" id="storeKey"><?php echo $storeKey; ?></span>
        <button id="updateBridgeStoreKey" class="btn-update-store-key">Update Store Key</button>
      </div>

      <button id="api2cartConnectionUninstall" class="btn-disconnect btn-setup">Disconnect</button>
      <button id="api2cartConnectionInstall" class="btn-connect btn-setup">Connect</button>

    </div>

    <input type="hidden" id="showButton" value="<?php echo $showButton; ?>">

    <div class="clearfix"></div>
  </div>

</div>
